const FlightDataInternational = [
  {
    index: 549,
    origin: "DXB",
    destination: "DEL",
    depart_time: "10:50:00",
    depart_weekday: 5,
    duration: "04:35:00",
    arrival_time: "15:25:00",
    arrival_weekday: 5,
    flight_no: "SG6",
    airline_code: "SG",
    airline: "SpiceJet",
    economy_fare: 15361,
    business_fare: "",
    first_fare: "",
  },
  {
    index: 550,
    origin: "DXB",
    destination: "DEL",
    depart_time: "12:50:00",
    depart_weekday: 5,
    duration: "05:30:00",
    arrival_time: "18:20:00",
    arrival_weekday: 5,
    flight_no: "IX142",
    airline_code: "IX",
    airline: "Air India Express",
    economy_fare: 15585,
    business_fare: "",
    first_fare: "",
  },
  {
    index: 551,
    origin: "DXB",
    destination: "DEL",
    depart_time: "12:50:00",
    depart_weekday: 6,
    duration: "05:30:00",
    arrival_time: "18:20:00",
    arrival_weekday: 6,
    flight_no: "IX142",
    airline_code: "IX",
    airline: "Air India Express",
    economy_fare: 15585,
    business_fare: "",
    first_fare: "",
  },
  {
    index: 555,
    origin: "DXB",
    destination: "DEL",
    depart_time: "10:50:00",
    depart_weekday: 4,
    duration: "04:35:00",
    arrival_time: "15:25:00",
    arrival_weekday: 4,
    flight_no: "SG6",
    airline_code: "SG",
    airline: "SpiceJet",
    economy_fare: 16391,
    business_fare: "",
    first_fare: "",
  },
  {
    index: 556,
    origin: "DXB",
    destination: "DEL",
    depart_time: "10:50:00",
    depart_weekday: 3,
    duration: "04:35:00",
    arrival_time: "15:25:00",
    arrival_weekday: 3,
    flight_no: "SG6",
    airline_code: "SG",
    airline: "SpiceJet",
    economy_fare: 16451,
    business_fare: "",
    first_fare: "",
  },
  {
    index: 557,
    origin: "DXB",
    destination: "DEL",
    depart_time: "10:50:00",
    depart_weekday: 6,
    duration: "04:35:00",
    arrival_time: "15:25:00",
    arrival_weekday: 6,
    flight_no: "SG6",
    airline_code: "SG",
    airline: "SpiceJet",
    economy_fare: 16451,
    business_fare: "",
    first_fare: "",
  },
  {
    index: 558,
    origin: "DXB",
    destination: "DEL",
    depart_time: "22:20:00",
    depart_weekday: 5,
    duration: "04:40:00",
    arrival_time: "03:00:00",
    arrival_weekday: 6,
    flight_no: "SG12",
    airline_code: "SG",
    airline: "SpiceJet",
    economy_fare: 16451,
    business_fare: "",
    first_fare: "",
  },
  {
    index: 559,
    origin: "DXB",
    destination: "DEL",
    depart_time: "00:05:00",
    depart_weekday: 6,
    duration: "04:40:00",
    arrival_time: "04:45:00",
    arrival_weekday: 6,
    flight_no: "AI996",
    airline_code: "AI",
    airline: "Air India",
    economy_fare: 16717,
    business_fare: "",
    first_fare: 52083,
  },
  {
    index: 561,
    origin: "DXB",
    destination: "DEL",
    depart_time: "12:50:00",
    depart_weekday: 4,
    duration: "05:30:00",
    arrival_time: "18:20:00",
    arrival_weekday: 4,
    flight_no: "IX142",
    airline_code: "IX",
    airline: "Air India Express",
    economy_fare: 17323,
    business_fare: "",
    first_fare: "",
  },
  {
    index: 562,
    origin: "DXB",
    destination: "DEL",
    depart_time: "12:50:00",
    depart_weekday: 3,
    duration: "05:30:00",
    arrival_time: "18:20:00",
    arrival_weekday: 3,
    flight_no: "IX142",
    airline_code: "IX",
    airline: "Air India Express",
    economy_fare: 17323,
    business_fare: "",
    first_fare: "",
  },
  {
    index: 563,
    origin: "DXB",
    destination: "DEL",
    depart_time: "10:50:00",
    depart_weekday: 2,
    duration: "04:35:00",
    arrival_time: "15:25:00",
    arrival_weekday: 2,
    flight_no: "SG6",
    airline_code: "SG",
    airline: "SpiceJet",
    economy_fare: 17600,
    business_fare: "",
    first_fare: "",
  },
  {
    index: 564,
    origin: "DXB",
    destination: "DEL",
    depart_time: "22:20:00",
    depart_weekday: 3,
    duration: "04:40:00",
    arrival_time: "03:00:00",
    arrival_weekday: 4,
    flight_no: "SG12",
    airline_code: "SG",
    airline: "SpiceJet",
    economy_fare: 17600,
    business_fare: "",
    first_fare: "",
  },
  {
    index: 565,
    origin: "DXB",
    destination: "DEL",
    depart_time: "22:20:00",
    depart_weekday: 4,
    duration: "04:40:00",
    arrival_time: "03:00:00",
    arrival_weekday: 5,
    flight_no: "SG12",
    airline_code: "SG",
    airline: "SpiceJet",
    economy_fare: 17600,
    business_fare: "",
    first_fare: "",
  },
  {
    index: 571,
    origin: "DXB",
    destination: "DEL",
    depart_time: "22:20:00",
    depart_weekday: 2,
    duration: "04:40:00",
    arrival_time: "03:00:00",
    arrival_weekday: 3,
    flight_no: "SG12",
    airline_code: "SG",
    airline: "SpiceJet",
    economy_fare: 18748,
    business_fare: "",
    first_fare: "",
  },
];

export default FlightDataInternational;
